import "./globals.css";
import Modals from "@/providers/modals-provider";
import ConvexClientProvider from "@/providers/convex-client-provider";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { montserrat } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Team Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <ConvexClientProvider>
          <Modals />
          <Toaster />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
